### ISSUE TITLE
Clicking on Select several files

### ISSUE THREAD

**Issue by ylaleo** [feup-infolab/dendro#19]
Add possibility to choose folders and files clicking on the square. most of the people trying click on it, and cant choose folder..

Select is function only clicking on the name of folder or files..
![3](https://cloud.githubusercontent.com/assets/22300858/19076054/3d58f00e-8a3f-11e6-8b9b-d538b48bd1d4.PNG)

**Comment by silvae86** [comment]
Fixed by 975fc4366d24dcebc5c87f754b4e4ad7b5869592
