### ISSUE TITLE
Different information on error message (1-0)

### ISSUE THREAD

**Issue by ylaleo** [feup-infolab/dendro#21]
![1](https://cloud.githubusercontent.com/assets/22300858/19076356/5e57f3da-8a40-11e6-86de-1104efdd9941.PNG)

![2](https://cloud.githubusercontent.com/assets/22300858/19076362/64c1e0be-8a40-11e6-8f39-e954b5bd08e7.PNG)

Descriptor Data - Add several at once - imagine that I did mistake with number and write 0..

**Comment by silvae86** [comment]
Fixed in #251
