### ISSUE TITLE
Descriptors were not uploaded from the ontologies (maybe)

### ISSUE THREAD

**Issue by ylaleo** [feup-infolab/dendro#265]
### Dendro Version if known (or site URL)

http://dendro-prd.fe.up.pt:3007

### What steps can be taken to reproduce the issue? 

1. Create project. Upload the file. 

2.  Does not exists any descriptor on the area of domains..

![capturar](https://user-images.githubusercontent.com/22300858/31667759-3b7b79e0-b348-11e7-8b5d-5c17097a8ab8.PNG)

!!! Its happened only with you dont choose any domain ..

I will create video for demonstrate better...

**Comment by silvae86** [comment]
Fixed in #282. The problem was recording the interactions of ontology selection, which stopped the ontology retrieval process.
