### ISSUE TITLE
Share does not work (appears a symbol "stop")

### ISSUE THREAD

**Issue by ylaleo** [feup-infolab/dendro#266]
### Dendro Version if known (or site URL)
http://dendro-prd.fe.up.pt:3007

### Please describe the expected behaviour

![2017-10-17 14_38_37-teste2 - dendro](https://user-images.githubusercontent.com/22300858/31668442-202a96ec-b34a-11e7-9a8b-ba1ac3fef5e2.png)

**Comment by silvae86** [comment]
Isto foi resolvido no #251, commit #1957a0b62b21d2036dd5343c4c6d5d9e82a02ce8, era a chave da configuração das plataformas.
