### ISSUE TITLE
File names that contain spaces are being saved with %20

### ISSUE THREAD

**Issue by NelsonPereira1991** [feup-infolab/dendro#271]
### Dendro Version if known (or site URL)
Tested in the branch [machine-plus-human-identifiers](https://github.com/feup-infolab/dendro/tree/machine-plus-human-identifiers)

In the [commit](https://github.com/feup-infolab/dendro/commit/938e26a4d09ee8f2298bcad83fc79eb1477dcb1d)

### Please describe the actual behaviour
Should upload and save the file correctly and with the spaces. For example "Social Dendro.pdf" cannot be saved as "Social%20Dendro.pdf".

### Please describe the actual behaviour
Is saving file "Social Dendro.pdf" as "Social%20Dendro.pdf".

![screen shot 2017-11-07 at 12 11 05](https://user-images.githubusercontent.com/6686528/32493237-079a766c-c3b5-11e7-9198-f80b1c845bb9.png)

### What steps can be taken to reproduce the issue? 
Upload a file that contains spaces in its name.

### Possible ways to fix the problem (programmers)
Handle special characters

**Comment by silvae86** [comment]
Fixed in #251 .
