### ISSUE TITLE
Dendro-UP - dont work "search for descriptor" - descriptor Title

### ISSUE THREAD

**Issue by ylaleo** [feup-infolab/dendro#31]
When I searching for descriptor Title, appear differents descriptor, one of this title with smal size letter  "title" but this descriptor about Mr, Ms, etc.

![111](https://cloud.githubusercontent.com/assets/22300858/19932614/a7a8dd36-a108-11e6-9447-a84e995d34c5.PNG)
![12](https://cloud.githubusercontent.com/assets/22300858/19932653/c425cf8c-a108-11e6-9432-0e675f07ef66.PNG)

**Comment by silvae86** [comment]
This is part of the FOAF ontology itself, we cannot change the label that they give to their properties.... I am closing this.
