### ISSUE TITLE
Dendro-UP - error on area "Editing project" after clicking Operations - Administer

### ISSUE THREAD

**Issue by ylaleo** [feup-infolab/dendro#32]
![221](https://cloud.githubusercontent.com/assets/22300858/19933367/01f81750-a10b-11e6-9997-bdd9b4fc3597.png)

![222](https://cloud.githubusercontent.com/assets/22300858/19933373/054159d0-a10b-11e6-8b59-c1da8c0d5589.PNG)

**Comment by silvae86** [comment]
Fixed in #251
