### ISSUE TITLE
[BUG] RDF used to export to repos is invalid

### ISSUE THREAD

**Issue by NelsonPereira1991** [feup-infolab/dendro#324]
### Dendro Version if known (or site URL)
https://github.com/feup-infolab/dendro/tree/machine-plus-human-identifiers

### Please describe the expected behaviour
Should export the dataset and the metadata information in various formats(txt,json,rdf) correctly

### Please describe the actual behaviour
The rdf file is being incorrectly built. The line xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" is written twice and should only be used once.

### What steps can be taken to reproduce the issue? 
Export a dataset via Dendro to b2share and then try to open the rdf file from the b2share web interface.

### Possible ways to fix the problem (programmers)
Check the code that builds the rdf files from the metadata info. All the other formats are correct so this must be only related to building rdf metadata files.

**Comment by rodavoce** [comment]
It's already solved.
Exported rdf example: 

> <?xml version="1.0" encoding="UTF-8"?>
<rdf:RDF
    xmlns:dcterms="http://purl.org/dc/terms/"
    xmlns:ddr="http://dendro.fe.up.pt/ontology/0.1/"
    xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
    xmlns:nie="http://www.semanticdesktop.org/ontologies/2007/01/19/nie#"
    xmlns:schema="http://schema.org/">
    <rdf:Description rdf:about="pp">
        <dcterms:description>pp</dcterms:description>
        <dcterms:title>pp</dcterms:title>
        <dcterms:creator>http://127.0.0.1:3001/r/user/13224f05-67c0-44d3-b0f7-920805e4dc8b</dcterms:creator>
        <dcterms:language>en</dcterms:language>
        <ddr:handle>pp</ddr:handle>
        <ddr:rootFolder>http://127.0.0.1:3001/r/folder/9dee779d-35ca-4e28-a7cc-4de83bba8d22</ddr:rootFolder>
        <ddr:modified>2018-02-02T23:07:14.296Z</ddr:modified>
        <ddr:humanReadableURI>http://127.0.0.1:3001/project/pp</ddr:humanReadableURI>
        <ddr:created>2018-01-16T20:55:51.569Z</ddr:created>
        <ddr:hasStorageLimit>1073741824</ddr:hasStorageLimit>
        <ddr:privacyStatus>private</ddr:privacyStatus>
        <ddr:hasStorageConfig>/r/storage_config/4a4228da-4171-41e6-8e19-ac249ae9f7a4</ddr:hasStorageConfig>
        <rdf:type>http://dendro.fe.up.pt/ontology/0.1/Project</rdf:type>
        <rdf:type>http://dendro.fe.up.pt/ontology/0.1/Resource</rdf:type>
        <nie:hasLogicalPart>http://127.0.0.1:3001/r/folder/9dee779d-35ca-4e28-a7cc-4de83bba8d22</nie:hasLogicalPart>
        <schema:license>Creative Commons Attribution 4.0</schema:license>
    </rdf:Description>
</rdf:RDF>
