### ISSUE TITLE
After dataset transfered to CKAN-UP and CKAN-Inesc we dont have access for view and download the files of the dataset with url correct (not 127.0.0.1)

### ISSUE THREAD

**Issue by ylaleo** [feup-infolab/dendro#33]
![1111](https://cloud.githubusercontent.com/assets/22300858/19933955/fb636096-a10c-11e6-8923-c5359b0d9794.PNG)
![1112](https://cloud.githubusercontent.com/assets/22300858/19933957/fde4e5c4-a10c-11e6-8edc-3effc34e7142.PNG)

**Comment by ylaleo** [comment]
1. I did one test on the CKAN-Inesc directly (without Dendro-Inesc): Added dataset with the image png, for check if we have access for view and download this dataset or not..
2. Yes we have access for view, preview and download this dataset
Result - during transfer the files from the Dendro-Inesc to CKAN -Inesc something happens and we lost access for this files.

**Comment by silvae86** [comment]
This was a configuration problem with the DataStore, solved.
