### ISSUE TITLE
We cant upload files docx

### ISSUE THREAD

**Issue by ylaleo** [feup-infolab/dendro#34]
1. Trying to upload this type of files.
2. Appear error 
![erro de upload docx](https://cloud.githubusercontent.com/assets/22300858/20031564/9ccaad16-a371-11e6-92c8-a59b67dbbfff.png)

3. And after that - User automatically doing log-off of the Dendro

![erro depois de erro de upload](https://cloud.githubusercontent.com/assets/22300858/20031583/bd20ac1e-a371-11e6-9a08-348de15a451d.PNG)

**Comment by silvae86** [comment]
Should be solved by 77ae916f10f26a0ba7b0b0f3348b9c610441a39e
