### ISSUE TITLE
Desapere description "Privacy" of the project 

### ISSUE THREAD

**Issue by ylaleo** [feup-infolab/dendro#35]
1. After de creation of the new project
2. Enter on Administer of the project - error
![editing project - error](https://cloud.githubusercontent.com/assets/22300858/20031923/b714ad1a-a377-11e6-8dbb-28ef50807b3c.PNG)
3.  And point of "Privacy" not indicated (in the moment of the creation I indicated Public)
![desapareceu privacy](https://cloud.githubusercontent.com/assets/22300858/20031929/e4d28010-a377-11e6-8f1d-508f6ddaf686.PNG)

**Comment by ylaleo** [comment]
Em que Dendro tu resolveste a problema? podes me indicar o link sff?

Verifiquei no http://dendro.inesctec.pt:3000/ - o erro está na mesmo...

**Comment by ylaleo** [comment]
![capturar](https://cloud.githubusercontent.com/assets/22300858/22737042/3d9338ae-edf9-11e6-9975-ca8a778d67d5.PNG)

e nem se quer grava se tento alterar...e gravar.. dendro logo vai abaixo..

**Comment by ylaleo** [comment]
aqui sao erros para ajudar
![capturar](https://cloud.githubusercontent.com/assets/22300858/22737107/7d7f20f4-edf9-11e6-9e96-e5b877775f7e.PNG)

**Comment by williamnf** [comment]
No meu caso, quando faço update, ele fica preso. Já tentei em versões não alteradas mas também têm esse problema. Isso não sei dizer o que é. Quanto a este bug, fiz uma alteração ao administer.js mas só me apercebi depois que tem mais lugares com a mesma variável. A minha hipótese é voltar o administer.ejs ao normal e modificar o new.ejs encarregue de criar um novo projecto de forma a que as variáveis fiquem com o mesmo nome

**Comment by ylaleo** [comment]
ja falei com Joao hoje...amanha testamos uma coisa..depois vemos se resolve o problema...fica para ja "pendurado"...

**Comment by silvae86** [comment]
Os nomes das variáveis do new.ejs estão bem, ou seja: 

Deve ser project.privacyStatus = public em vez de project.privacyStatus = publicStatus (não faz sentido repetir o "Status" nos dois lados, digo eu. É a isso te referes @williamnf ?

**Comment by williamnf** [comment]
Estava a falar dos radio buttons do new.ejs. Têm valores public private e metadata. Mas nos outros lugares têm com publicStatus... Mas eu pensava que era só no administer.ejs então não fazia diferença em qual mudava
