### ISSUE TITLE
Zenodo repository upload failure

### ISSUE THREAD

**Issue by williamnf** [feup-infolab/dendro#351]
### Please describe the expected behaviour
Upload successfully to a Zenodo repository

### Please describe the actual behaviour
Returns an error
"The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again."

### What steps can be taken to reproduce the issue? 
Try an upload to http://www.zenodo.org

**Comment by NelsonPereira1991** [comment]
fixed in https://github.com/feup-infolab/dendro/pull/358
