### ISSUE TITLE
[Firefox] download  of RDF, Text, JSON dont work

### ISSUE THREAD

**Issue by rodavoce** [feup-infolab/dendro#352]
### Dendro Version if known (or site URL)

https://github.com/feup-infolab/dendro/commit/7fe9a16b9fb1c31a8651e2ee324827a9f64f3d01

### Please describe the expected behaviour

Save Button to get RDF, JSON, TEXT inside the project should start file download

### Please describe the actual behaviour

Save button don't start download

### What steps can be taken to reproduce the issue? 

Browser:  Firefox Quantum- 58.0.2 (64-bit) - Mozilla Firefox for Ubuntu canonical - 1.0 

1. Open a project
2. Click save button on top corner

**Comment by NelsonPereira1991** [comment]
fixed in https://github.com/feup-infolab/dendro/pull/378
