### ISSUE TITLE
Permissions error on empty timeline

### ISSUE THREAD

**Issue by mgpsp** [feup-infolab/dendro#375]
### Dendro Version if known (or site URL)

post-ranking

### Please describe the expected behaviour

1. Timeline should not show a permissions error when there are no posts
2. After a manual post, the timeline should refresh and show all the posts

### Please describe the actual behaviour

1. Timeline shows a permissions error when there are no posts
2. After a manual posts, timeline refreshes, shows no posts and gives a permissions error. On refresh, timeline shows posts as it should.

### What steps can be taken to reproduce the issue? 

For issue 1, go to an empty timeline
For issue 2, try to make a manual post

### Possible ways to fix the problem (programmers)

**Comment by NelsonPereira1991** [comment]
fixed in https://github.com/feup-infolab/dendro/pull/376
