### ISSUE TITLE
When i add many files (+/- 35) at the same time, Dendro- Inesc is blocked

### ISSUE THREAD

**Issue by ylaleo** [feup-infolab/dendro#38]
1. Create new project
2. Create new folder
3. Upload 35files mp3 with size more or less 4-9mb each one of them
4. Dendro is blocked and to describe each file, i need to refresh page..but is work very very slowly and i  could to describe nothing.

**Comment by silvae86** [comment]
Should be solved by 77ae916f10f26a0ba7b0b0f3348b9c610441a39e, which implements streaming file simultaneous uploads, queued.
