### ISSUE TITLE
Problems loading ontologies

### ISSUE THREAD

**Issue by rizzoli** [feup-infolab/dendro#394]
### Dendro Version if known (or site URL)
Installed locally from docker image

### Please describe the expected behaviour
Click on the "manual selection" tab, see a list of ontologies. Select one ontology, view the list of triple, select one and fill in the metadata..

### Please describe the actual behaviour
Click on the "manual selection" click on "Friend of a Friend", a list of ontologies appears, click on "Dublin Core terms", try to expand DC, but get a message "Unable to register interaction
Unable to register manual selection of the ontology Dublin Core terms!" in a red pop up box 

### What steps can be taken to reproduce the issue? 
Try to install Dendro in Docker, log in as demo user (but as registered user the behaviour does not change), upload a data set and try to annotate it
![Screenshot 2019-07-23 at 09 01 59](https://user-images.githubusercontent.com/9379792/61689972-8bf69180-ad28-11e9-98de-36e48a24e79e.png)

### Possible ways to fix the problem (programmers)

**Comment by silvae86** [comment]
#Why I think this happens

This may be because of the way we have configure virtuoso on the first startup, because ontologies are loaded into virtuoso once and then there is no need to load them anymore. 

On some occasions, and during this first startup, dendro will try to interact with virtuoso, but virtuoso is still loading the ontologies.... it will then cause errors.

# possible fix

Please try to restart dendro (`docker-compose stop` followed by `docker-compose start`) or Ctrl+C, wait for clean shutdown, `docker-compose up`).

If it does not fix the issue, please tell us.

Thanks,
João Rocha da Silva

**Comment by silvae86** [comment]
(I am writing on my iphone and cannot edit the text after posting, so please forgive the mistakes in the text)

**Comment by rizzoli** [comment]
Thanks João! We have followed your instructions, but still the error persists. I am sure it is something in the configuration. I attach the output of the Dendro instance:
dendro           | 2019-07-23T09:10:36.199Z [development] info: Unknown error occurred! About to exit with code 1
dendro           | 2019-07-23T09:10:36.200Z [development] info: Waiting for pending connections to finish up...
mongodb-dendro   | 2019-07-23T09:10:36.208+0000 I NETWORK  [conn17] end connection 172.19.0.6:38098 (10 connections now open)
mongodb-dendro   | 2019-07-23T09:10:36.208+0000 I NETWORK  [conn18] end connection 172.19.0.6:38100 (8 connections now open)
mongodb-dendro   | 2019-07-23T09:10:36.208+0000 I NETWORK  [conn20] end connection 172.19.0.6:38106 (11 connections now open)
mongodb-dendro   | 2019-07-23T09:10:36.208+0000 I NETWORK  [conn16] end connection 172.19.0.6:38096 (7 connections now open)
mongodb-dendro   | 2019-07-23T09:10:36.208+0000 I NETWORK  [conn15] end connection 172.19.0.6:38094 (6 connections now open)
mongodb-dendro   | 2019-07-23T09:10:36.208+0000 I NETWORK  [conn13] end connection 172.19.0.6:38090 (5 connections now open)
mongodb-dendro   | 2019-07-23T09:10:36.208+0000 I NETWORK  [conn21] end connection 172.19.0.6:38108 (4 connections now open)
mongodb-dendro   | 2019-07-23T09:10:36.208+0000 I NETWORK  [conn19] end connection 172.19.0.6:38102 (9 connections now open)
mongodb-dendro   | 2019-07-23T09:10:36.208+0000 I NETWORK  [conn22] end connection 172.19.0.6:38110 (3 connections now open)
mongodb-dendro   | 2019-07-23T09:10:36.209+0000 I NETWORK  [conn12] end connection 172.19.0.6:38076 (2 connections now open)
mongodb-dendro   | 2019-07-23T09:10:36.209+0000 I NETWORK  [conn11] end connection 172.19.0.6:38074 (1 connection now open)
mongodb-dendro   | 2019-07-23T09:10:36.209+0000 I NETWORK  [conn10] end connection 172.19.0.6:38072 (0 connections now open)
dendro           | npm ERR! code ELIFECYCLE
dendro           | npm ERR! errno 1
dendro           | npm ERR! dendro@0.3.0 start: `node src/app.js`
dendro           | npm ERR! Exit status 1
dendro           | npm ERR!
dendro           | npm ERR! Failed at the dendro@0.3.0 start script.
dendro           | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
dendro           |
dendro           | npm ERR! A complete log of this run can be found in:
dendro           | npm ERR!     /home/dendro/.npm/_logs/2019-07-23T09_10_36_214Z-debug.log

**Comment by rizzoli** [comment]
The nom log is not very informative anyway

**Comment by silvae86** [comment]
Hi Andrea,

Is that the full log or just an excerpt? I believe the real error can be a few lines up, can you get more lines from the beginning of booting up dendro? 

# seeing the docker log
Docker logs all console output, so if you type ‘docker logs dendro’ you should see the full log history, including startups and shutdowns. 

# seeing the log files

Dendro also saves the logs to .log files, besides the console output that you see in docker. 

Where you ran ‘docker-compose up’ you will find a volumes/ folder that contains the data of all services for quick backup and restore of the entire dendro instance. 

Look for a dendro/logs/docker folder inside. Then you should see several logs with dates. Please send me the full log file if you can.

Enviado do meu iPhone

No dia 23/07/2019, às 10:12, Andrea Rizzoli <notifications@github.com> escreveu:

**Comment by rizzoli** [comment]
I have piped the output of the docker log into the attached file. I hope this is what you needed 
[dendro.log](https://github.com/feup-infolab/dendro/files/3421415/dendro.log)

**Comment by silvae86** [comment]
Yep, that’s it! Thanks.

I think I saw the issue already, give me a little time to investigate further. I will get back to you.

João 

Enviado do meu iPhone

No dia 23/07/2019, às 11:00, Andrea Rizzoli <notifications@github.com> escreveu:

**Comment by rizzoli** [comment]
Great, take it easy, no hurry. I was interested in Dendro as a tool to annotate the data we are producing in the context of a EU funded project (www.encompass-project.eu). I was interested in the semantic annotations of the metadata which are a quite unique feature of your tool

**Comment by silvae86** [comment]
Hello Andrea,

# my conclusions
According to the log, your dendro version is running using commit with hash 5123b4182bca199f0384a31d9b9aebd746127ade, which is from July 2018 (quite old code). I was seeing the log and none of it made sense (functions no longer there, etc.) so it pointed me towards the conclusion that your version is outdated.

Is this dendro installation being used actively? Do you have data that you want to keep, or can we update the images?

# if you can destroy the existing instance

If we can destroy the existing data and update the system, please go to your dendro folder and run:

- `docker-compose down #stop containers`
- `docker-compose rm #remove containers`
- `rm -rf ./volumes # this one is what will destroy your data. If you want to save the data, copy the volumes/ folder to somewhere else.`
- `git checkout master; git pull #update dendro docker-compose.yml`,
- `docker-compose pull; docker-compose up #pull latest images, start up with new code`

João

**Comment by silvae86** [comment]
> Great, take it easy, no hurry. I was interested in Dendro as a tool to annotate the data we are producing in the context of a EU funded project ([www.encompass-project.eu](http://www.encompass-project.eu)). I was interested in the semantic annotations of the metadata which are a quite unique feature of your tool

This is really interesting! We are very interested in adoption stories and suggestions for improvements. You will also be pleased to know that Dendro now supports deposit and faceted search for datasets on the home page as per @lazarocosta 's recent work :)

**Comment by silvae86** [comment]
The deposit module supports DOI attribution and means that you no longer require a CKAN, ePrints or similar solution to deposited your Dendro finished datasets for them to be citable. 

Dendro still supports dataset exporting to external repositories, so you are free to use any repository as you could before.

**Comment by rizzoli** [comment]
Thanks for the help. We reinstalled everything and the situation has definitely improved, yet there are a couple of things that still don't work. 

This is the version we have now installed: Version: dendro. v.1.0.0-beta Active Branch: master Commit: 16fe463def00ef5318a6d2f036db7e8d95ff00c5 Date Tue Jul 23 11:48:14 2019 +0100

### First issue

The ontologies appear to have loaded, but then when I try to select (for instance) the "Dublin Core terms" a text appears ("fetching descriptors etc etc") very briefly, then the list of terms appears but only for a second and then the right menu collapses back to "Dublin Core terms" and there's no way I can add metadata to my dataset. I attach at the bottom the output I can observe in the Dendro console.

```dendro           | 2019-07-24T07:16:15.821Z [development] info: Interaction of type select_ontology_manually over resource http://purl.org/dc/terms/ in the context of resource /r/file/95711280-63b8-4037-9b93-86c6a53fc100 recorded successfully
dendro           | 2019-07-24T07:16:15.823Z [development] info: POST /interactions/select_ontology_manually 200 79ms
dendro           | 2019-07-24T07:16:15.948Z [development] info: GET /r/file/95711280-63b8-4037-9b93-86c6a53fc100?descriptors_from_ontology=dcterms 200 197ms
dendro           | 2019-07-24T07:16:16.003Z [development] info: GET /r/file/95711280-63b8-4037-9b93-86c6a53fc100?metadata_recommendations&current_metadata=%5B%5D&page=1&page_size=25&recommend_already_filled_in=false 200 169ms
virtuoso-dendro  | 07:17:00 Checkpoint started
virtuoso-dendro  | 07:17:00 Checkpoint finished, log reused
```

If this issue is not clear, I can try to to a screen recording to show you what's going on.

###  Second issue
A second issue is when one creates a new project. Everything goes fine, but the progress bar gets stuck near the end
![Screenshot 2019-07-24 at 09 20 46](https://user-images.githubusercontent.com/9379792/61773187-561edf00-adf4-11e9-89dd-32524dfc5bdc.png)

Probably they are related, but maybe there's a specific log file that could be helpful to identify the problem?

**Comment by silvae86** [comment]
Let’s first try an easy thing. Please log out and clear the browser cache. There may be some malformed client data from the older instance interfering with the new code. 

Enviado do meu iPhone

No dia 24/07/2019, às 08:28, Andrea Rizzoli <notifications@github.com> escreveu:

**Comment by rizzoli** [comment]
A good suggestion, but unfortunately it did not solve the problem. I tried with different browsers after having cleared out the cache, but still the same problem which you can see in the attached screencast
[dendro.mov.zip](https://github.com/feup-infolab/dendro/files/3425902/dendro.mov.zip)

**Comment by silvae86** [comment]
I am glad you got it working. I was just testing both a docker-based installation and a source-based installation. The docker-based one hangs indefinitely after creating the project, but when Dendro is run from source it does not hang 😮 

Tough bug to catch, because inside Docker we cannot step through the code. I think it must be a callback inside that is not getting called under certain circumstances because the request to create the project stays pending indefinitely. 

We will investigate this bug and get back to you!

**Comment by rizzoli** [comment]
Ok, thanks. In the meantime I keep trying out the various features. Currently I am having problems uploading a dataset on a repository (tells me it cannot find the file I want to upload), but in case I don't sort this out, I will create a different issue than this one.

**Comment by silvae86** [comment]
Which repository are you trying to upload to?

João

**Comment by rizzoli** [comment]
EUDAT b2share in the test version of the repo
