### ISSUE TITLE
http://rdm-demo.up.pt:5000/ and http://rdm-demo.up.pt:3000/ dont work (14.11.2016)

### ISSUE THREAD

**Issue by ylaleo** [feup-infolab/dendro#43]
![1](https://cloud.githubusercontent.com/assets/22300858/20261848/8b186634-aa57-11e6-9cb3-7941db78fa8b.PNG)
![2](https://cloud.githubusercontent.com/assets/22300858/20261851/8cf36a12-aa57-11e6-8d3d-71035ef8c40f.PNG)

**Comment by silvae86** [comment]
This is now solved.
