### ISSUE TITLE
transferencia de todos os dados de projeto (até eliminados tambem)

### ISSUE THREAD

**Issue by ylaleo** [feup-infolab/dendro#53]
explico: no dendro eu tinha projeto onde ja tinha mp3 depois eliminava depois tinha mais coisas depois eliminava depois tentava transferir para inesc. e entretanto agora no momento de teste da transferencia ele transferiu me e aqueles mp3 que no moemtno actual já nao existiam mais no projeto e ouros ficheiros que ja nao sei de onde foi buscar pois ja nao me lembro o que havia nesta pasta. 
Tenho de vertificar mais ..

**Comment by silvae86** [comment]
@NelsonPereira1991 isto foi resolvido, certo?

**Comment by NelsonPereira1991** [comment]
@ylaleo @silvae86 Sim foi resolvido, mas tens mesmo de apagar no Dendro os ficheiros para eles deixarem de existir no Ckan. Não basta apenas marcar como "deleted".
