### ISSUE TITLE
Juntar informaçao de dois description (no inesc)

### ISSUE THREAD

**Issue by ylaleo** [feup-infolab/dendro#54]
Durante transferencia obrigatoriamente pede se adicionar description no Dendro (inesc) eu adicionei
e ele transferiu os dados, mas depois no datasets (no inesc) aparece mensagem This dataset has no description...mas dentro de dataset sim existe description..entao nao podiam juntar se essas dois description?

**Comment by silvae86** [comment]
@NelsonPereira1991 Isto foi resolvido no #282 , certo? O módulo de depósito no CKAN já produz os metadados corretos, não é? Se sim, fecha a issue.

**Comment by NelsonPereira1991** [comment]
@ylaleo @silvae86 Sim também já foi resolvido. Vou fechar.

Fixed in https://github.com/feup-infolab/dendro/tree/machine-plus-human-identifiers
