### ISSUE TITLE
After creation new project and added description (Dendro-Inesc) - Information dont save

### ISSUE THREAD

**Issue by ylaleo** [feup-infolab/dendro#58]
1. Creating new project with this description
<img width="921" alt="3" src="https://cloud.githubusercontent.com/assets/22300858/21222566/5e49cda2-c2ba-11e6-8c96-d04945190079.PNG">
2. 
<img width="899" alt="2" src="https://cloud.githubusercontent.com/assets/22300858/21222574/6910ab34-c2ba-11e6-9c57-7c2ea97d4e87.PNG">
3. Created folder tabelametricas and added files tabela metricas.ods and description like this
<img width="952" alt="1" src="https://cloud.githubusercontent.com/assets/22300858/21222615/96e49f48-c2ba-11e6-9198-bde57172eed1.PNG">

Click buttom SAVE and nothing happen!!
Try to move to project I have Warning like this:
<img width="939" alt="depois de clicar save - apareceu me aviso" src="https://cloud.githubusercontent.com/assets/22300858/21222632/bbe04d60-c2ba-11e6-8978-c6be14d0d4a8.PNG">

**Comment by ylaleo** [comment]
Saved - after several times clicking save ... and waiting long time without "touching" the page .... dont see any message, any warning...nothing..

**Comment by ylaleo** [comment]
message of error of the console web in browser
![guardar](https://cloud.githubusercontent.com/assets/22300858/21772288/7df4fbdc-d682-11e6-8b00-1fc0a7019867.PNG)

**Comment by silvae86** [comment]
Had to do with Angular version, which deprecated .success() calls. The code is now refactored to angular 1.6*

Solved by 77ae916f10f26a0ba7b0b0f3348b9c610441a39e
