### ISSUE TITLE
Dont work transfer to B2Share (Dendro-Inesc) with option use Dendro acount

### ISSUE THREAD

**Issue by ylaleo** [feup-infolab/dendro#59]
According thesis the Fabio (pp 40-4.2. B2Share, the External Repository for Data and Metadata - If researchers wanted to deposit their data directly through B2Share’s webpage, they would have to create an account, download all their project from Dendro, upload it to B2Share and describe it all over again. However, that requires a lot of effort from them, which is not what we want and it is against the homogeneous process we are looking for. Therefore, our integration module connects the two ends and allows researchers to export their data directly via Dendro.....
All requests to the API require a token generated by B2Share. A B2Share account for Dendro
was created and the corresponding token is used for the communication. All records are deposited
into Dendro’s account, unless researchers have a B2Share account of their own. In that case,
they can use their token by the time of the deposit, and all data will go into their account.)

I tested to transfer dataset to B2Share (Dendro -Inesc) with Use Dendro acount - Sending...without stopping....and nothing transfered..
![imagem](https://cloud.githubusercontent.com/assets/22300858/21229049/29271a9e-c2d8-11e6-8d72-9558cca4a6b4.png)

![imagem](https://cloud.githubusercontent.com/assets/22300858/21229069/38195026-c2d8-11e6-8eb4-1b83c8901987.png)

**Comment by silvae86** [comment]
B2Share deposit has been fixed by @NelsonPereira1991 with the b2share wrapper.
