### ISSUE TITLE
Ckan Inesc tec - datasets more or less 100MB are not possibile to upload (File upload too large)

### ISSUE THREAD

**Issue by ylaleo** [feup-infolab/dendro#69]
We have datasets to upload and describe more than 100MB..

![erro de tamanho ckan inesc_3](https://cloud.githubusercontent.com/assets/22300858/21988577/b65c9caa-dbff-11e6-8fde-7466353a1469.PNG)
![erro de tamanho ckan inesc](https://cloud.githubusercontent.com/assets/22300858/21988578/b65fa288-dbff-11e6-9622-a4e3098a28ca.PNG)
![erro de tamanho ckan inesc_2](https://cloud.githubusercontent.com/assets/22300858/21988579/b6617a9a-dbff-11e6-8c1c-826bf591634d.PNG)

**Comment by silvae86** [comment]
Fixed with editing `/etc/ckan/default/development.ini`

```ini
## Storage Settings

#ckan.storage_path = /var/lib/ckan
ckan.max_resource_size = 1000 #1000MB
ckan.max_image_size = 500 #500MB (overkill for an image...)


```
