### ISSUE TITLE
(Social Extension) Post was associated to a Change done by a user other than the currently authenticated one

### ISSUE THREAD

**Issue by silvae86** [feup-infolab/dendro#79]
User A added Abstract and Alternative Title descriptors.
User B added also the same descriptors.

Posts were generated, but the Post generated for the changes made by User A contains the values put by User B.

Abstract feito por mcr devia ter como autor mcr mas tem autor joana.

**Comment by NelsonPereira1991** [comment]
@silvae86  This is now fixed in the machine-identifiers branch
