### ISSUE TITLE
Registration form - add sugestion for field "Username" like field "Handle"(new project)

### ISSUE THREAD

**Issue by ylaleo** [feup-infolab/dendro#8]
Or write text that appear on message the error. "Username can not include spaces or special characters..etc..

Because, many people try to register and have problem with choose username. As I told in the other sugestion, all information completed will eliminate. It is not very comfortable repeat to fill the information, for exemplo on the filed "description".

**Comment by silvae86** [comment]
Solved since @williamnf remade the registration form. Now there is Regex-based validation of the fields.
